export const ADD_TODO = "ADD_TODO";
export const MARK_AS_COMPLETE = "MARK_AS_COMPLETE";
export const DELETE_TODO = "DELETE_TODO";
export const SELECT_TODO = "SELECT_TODO";
export const UPDATE_TODO = "UPDATE_TODO";
export const MARK_ALL_AS_DONE = "MARK_ALL_AS_DONE";
export const DELETE_ALL_COMPLETED = "DELETE_ALL_COMPLETED";
